story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('story1', views.index, name='index'),
]

story4/urls.py
from django.urls import path

from . import views

app_name = 'story4'

urlpatterns = [
    path('', views.home, name='homeku'),
    path('about',views.about,name = 'about'),
    path('experiences',views.experiences, name = 'experiences'),
    path('abilities',views.abilities,name = 'abilities'),
    path('hobby',views.hobby,name = 'Hobby'),
    path('story1',views.tes,name = 'tes')
]

webpli/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story1.urls')),
    path('', include('story4.urls')),
]

story1/models.py
from django.db import models

# Create your models here.

story4/models.py
from django.db import models

# Create your models here.

story1/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'story1/tes.html')

story4/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'story4/homeku.html')

def about(request):
    return render(request, 'story4/about.html')

def experiences(request):
    return render(request, 'story4/experiences.html')

def abilities(request):
    return render(request, 'story4/abilities.html')

def hobby(request):
    return render(request, 'story4/Hobby.html')

def tes(request):
    return render(request, 'story1/tes.html')

story1/templates/story1/tes.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>Bismillah</title>
    <link rel="stylesheet" href="{% static 'story1/coba.css' %}">
</head>  
<body>
  
      <div id="header">
        <h1> Welcome to My Website</h1>
      </div>
<div id = "profile">
    <img src="{% static 'story1/images/mukaku.jpg' %}" alt="" width="150" height="auto" >
</div>
<div id = "main">
<table style="width: auto;">
  <tr>
    <td>Nama</td>
    <td>Muhammad Rafli Amardito</td> 
  </tr>
  <tr>
    <td>NPM</td>
    <td>1906307523</td>
  
  </tr>
  <tr>
    <td>Angkatan</td>
    <td><a href="https://maung.id/muhammad.rafli91" target="_blank"> <i>MAUNG 2019</i></a></td></td>
   
  </tr>
  <tr>
    <td>Student of</td>
    <td>Fasilkom Universitas Indonesia </td>     
  </tr>
  <tr>
      <td>Hobi</td>
      <td>Bermain game Fifa</td>
  </tr>
</table>

<h2> Deskripsi Diri</h2>
<h4> Saya lahir di Jakarta pada tanggal 12 Agustus 2001. Saya adalah anak kedua dari dua bersaudara. Sejak SMA saya ingin sekali bisa masuk di Universitas Indonesia. Saya adalah fans berat dari klub sepakbola FC Barcelona. Oleh karena itu warna background Website saya campuran antara warna merah dan biru. Saya masih pemula dalam hal membuat dan merancang web.</h4>

    <h2>Riwayat Pendidikan</h2>
    
    <table>
      <tr>
        <th>Jenjang Pendidikan</th>
        <th>Tahun</th> 
      </tr>
      <tr>
        <td>Universitas Indonesia</td>
        <td>2019-sekarang</td>
      
      </tr>
      <tr>
        <td>SMAN 54 Jakarta</td>
        <td>2016-2019</td>
       
      </tr>
      <tr>
        <td>SMPN 52 Jakarta</td>
        <td>2013 - 2016</td>     
      </tr>
      <tr>
          <td>SDN CC 02</td>
          <td>2007-2013</td>
      </tr>
    </table>
  </style>
  </div>
    <div id="socmed">
      <h2>Social Media</h2>
      <a href="https://www.instagram.com/rafliamardito/" target="_blank">
        <img class="sospli" src="{% static 'story1/images/instagram.png' %}" alt="" alt="Ig @rafliamardito" width="50" height="50" hspace="20"/>
      </a>
      <a href="https://www.facebook.com/muhammadrafli.amardito" target="_blank">
        <img class="sospli" src="{% static 'story1/images/facebook.png' %}" alt="" width="50" height="50" hspace="20"/>
      </a>
      <a href="https://www.linkedin.com/in/rafli-amardito-2533bb192/" target="_blank">
        <img class="sospli" src="{% static 'story1/images/linkedin.png' %}" alt="" width="50" height="50" hspace="20"/>
      </a>
  </div>

  <div id="footer">
      Copyright &copy; 2020 M. Rafli Amardito.
  </div>
  </body>
  
</html>

story4/templates/story4/Hobby.html
{% extends 'story4/base.html'%} {% load static %} {% block content %}
<head>
    
    <link rel="stylesheet" href="{% static 'story4/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'story4/fix.css' %}">
</head>    
        <div id="classes" class="layout_padding">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text_align_center">
                        <h2 class="heading_section" style="margin-bottom: 65px;">Hobby</h3>
                    </div>
                </div>
                <div class="row">
    
                    <div class="col-md-4">
                        <div class="full dance_form_name">
                            <img src="{% static 'story4/images/jordan.jpg' %}" alt="" width="246" height="246">
                            <h4>Basketball</h4>
                        </div>
                    </div>
    
                    <div class="col-md-4">
                        <div class="full dance_form_name">
                            <img src="{% static 'story4/images/fifa.jpg' %}" alt="" width="246" height="246">
                            <h4>Fifa</h4>
                        </div>
                    </div>
    
                    <div class="col-md-4">
                        <div class="full dance_form_name">
                            <img src="{% static 'story4/images/futsal.jpg' %}" alt="" width="246" height="246">
                            <h4>Futsal</h4>
                        </div>
                    </div>
                    <div id="classes" class="layout_padding">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-12 text_align_center">
                                    <h2 class="heading_section" style="margin-bottom: 65px;">Interest</h3>
                                </div>
                            </div>
                            <div class="row">
    
                    <div class="col-md-4">
                        <div class="full dance_form_name">
                            <img src="{% static 'story4/images/bisnis.jpg' %}" alt="#" />
                            <h4>Business</h4>
                        </div>
                    </div>
    
                    <div class="col-md-4">
                        <div class="full dance_form_name">
                            <img src="{% static 'story4/images/teknologi.png' %}" alt="#" />
                            <h4>Technology</h4>
                        </div>
                    </div>
    
                     <div class="col-md-4">
                        <div class="full dance_form_name">
                            <img src="{% static 'story4/images/entre.jpg' %}" alt="#" />
                            <h4>Entrepreneur</h4>
                        </div>
                    </div>
    
                </div>
            </div>
        </div>

{% endblock %}

story4/templates/story4/abilities.html
{% extends 'story4/base.html'%} {% load static %} {% block content %}  
   
<section id="skill">
    <div class="skill container">
        <div class="skill-top">
            <h1 class="section-title">SKILLS</h1>
        </div>
        <div class="skill-bottom">
            <div class="skill-item">
                <h1>Leadership</h1>
                <div class="icon"><img src="{% static 'story4/images/star-leadership.png' %}" /></div>
            </div>
            <div class="skill-item">
                <h1>Public Speaking</h1>
                <div class="icon"><img src="{% static 'story4/images/star-public-speak.png' %}" /></div>
            </div>
            <div class="skill-item">
                <h1>Python</h1>
                <div class="icon"><img src="{% static 'story4/images/star-python.png' %}" /></div>
            </div>
            <div class="skill-item">
                <h1>Team Management</h1>
                <div class="icon"><img src="{% static 'story4/images/star-team-manage.png' %}" /></div>

            </div>
        </div>
    </div>
</section>
{% endblock %}

story4/templates/story4/about.html
{% extends 'story4/base.html'%} {% load static %} {% block content %}  
   
<div class="background-white">
    <div id="profile" class="container">
        <h2>Profile</h2>
        <p class="lead">I'm a creative webdeveloper</p>

        <hr>
        <div id = "profile">
        <img id="mukaku" src="{% static 'story4/images/mukaku.jpg' %}"alt="" width="246" height="246" style="margin: auto;">
        </div>

        <div class="row">
            <div class="col-md-4">
                <h3>About me</h3>
                <p>
                    im a student of University of Indonesia. I love to playing video games  , futsal, and also basketball, i like about business stuff. </p>
            </div>
            <div class="col-md-4">
                <h3>Details</h3>
                <p>
                    <strong>Name:</strong><br> Muhammad Rafli Amardito<br>
                    <strong>Age:</strong><br> 19 years<br>
                    <strong>Location:</strong><br> Jakarta, Indonesia, Earth <br>
                    <strong>NPM:</strong><br> 1906307523
                </p>
            </div>
        </div>
    </div>
{% endblock %}

story4/templates/story4/base.html
<!DOCTYPE html>
{% load static %}
 <html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <title>HOME-STORY 3</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'story4/fix.css' %}">
    
</head>

<body id="top">

    <div id="header-content">
    
        <nav class="row header-nav-wrap">
            <ul class="header-nav">
                <li><a class="smoothscroll"  href="{% url 'story4:homeku' %}" title="">Home</a></li>
                <li><a class="smoothscroll"  href="{% url 'story4:about' %}" title="">Profile</a></li>
                <li><a class="smoothscroll"  href="{% url 'story4:experiences' %}" title="">Experiences</a></li>
                <li><a class="smoothscroll"  href="{% url 'story4:abilities' %}" title="">Abilities</a></li>
                <li><a href="{% url 'story4:Hobby' %}" title="">Hobby&Interest</a></li>
                <li><a href="{% url 'story1:index' %}" title="">My Another Website</a></li>
            </ul>
        </nav>
    </div>
    {% block content %} {% endblock %}
    <div id="footer">
        Copyright &copy; 2020 M. Rafli Amardito.
    </div>
</body>

</html>

story4/templates/story4/experiences.html
{% extends 'story4/base.html'%} {% load static %} {% block content %}  

        <div class="row">
            <div class="column">
                <h3 data-aos="fade-up">Education</h3>
            </div>
        </div>
        

        <div class="row block-large-1-2 block-900-full work-positions">

            <div class="column" data-aos="fade-up">
                <div class="position">
                    <div class="position__header">
                        <h6>
                            <span class="position__co">University of Indonesia</span>
                        </h6>
                        <div class="position__timeframe">
                             2019 - present
                        </div>
                    </div>

                </div>
            </div>
            <div class="row block-large-1-2 block-900-full work-positions">

                <div class="column" data-aos="fade-up">
                    <div class="position">
                        <div class="position__header">
                            <h6>
                                <span class="position__co">54 Senior High School</span>
                            </h6>
                            <div class="position__timeframe">
                                 2016-2019
                            </div>
                        </div>
    
                    </div>
                </div>
                <div class="row block-large-1-2 block-900-full work-positions">

                    <div class="column" data-aos="fade-up">
                        <div class="position">
                            <div class="position__header">
                                <h6>
                                    <span class="position__co">54 junior High School</span>
                                </h6>
                                <div class="position__timeframe">
                                     2013-2016
                                </div>
                            </div>
        
                        </div>
                    </div>
                    <div class="row block-large-1-2 block-900-full work-positions">

                        <div class="column" data-aos="fade-up">
                            <div class="position">
                                <div class="position__header">
                                    <h6>
                                        <span class="position__co">02 Elementary School</span>
                                    </h6>
                                    <div class="position__timeframe">
                                         2007-2013
                                    </div>
                                </div>
            
                            </div>
                        </div>
            
        </div>

        <div class="row">
            <div class="column">
                <h3 data-aos="fade-up">Personal experiences</h3>
            </div>
        </div>
        <div class="row block-large-1-2 block-900-full work-positions">

            <div class="column" data-aos="fade-up">
                <div class="position">
                    <div class="position__header">
                        <h6>
                            <span class="position__co">Person in charge Liaison Officer of Open House Fasilkom UI 2020</span>
                        </h6>
                        <div class="position__timeframe">
                             June 2020-present
                        </div>
                    </div>

                </div>
            </div>
            <div class="row block-large-1-2 block-900-full work-positions">

                <div class="column" data-aos="fade-up">
                    <div class="position">
                        <div class="position__header">
                            <h6>
                                <span class="position__co">Staff Public Relation of Executive Council of Student CS UI</span>
                            </h6>
                            <div class="position__timeframe">
                                 Februari 2020- Present
                            </div>
                        </div>
    
                    </div>
                </div>
                <div class="row block-large-1-2 block-900-full work-positions">

                    <div class="column" data-aos="fade-up">
                        <div class="position">
                            <div class="position__header">
                                <h6>
                                    <span class="position__co">Staff food & beverages of COMPFEST XII</span>
                                </h6>
                                <div class="position__timeframe">
                                     2020
                                </div>
                            </div>
        
                        </div>
                    </div>
                    <div class="row block-large-1-2 block-900-full work-positions">

                        <div class="column" data-aos="fade-up">
                            <div class="position">
                                <div class="position__header">
                                    <h6>
                                        <span class="position__co">Staff Games of PERAK 2020</span>
                                    </h6>
                                    <div class="position__timeframe">
                                         2020
                                    </div>
                                </div>
            
                            </div>
                        </div>
                        <div class="row block-large-1-2 block-900-full work-positions">

                            <div class="column" data-aos="fade-up">
                                <div class="position">
                                    <div class="position__header">
                                        <h6>
                                            <span class="position__co">Staff equipment of Fasilkom’s graduation 2020</span>
                                        </h6>
                                        <div class="position__timeframe">
                                             2020
                                        </div>
                                    </div>
                
                                </div>
                            </div>
        
{% endblock %}

story4/templates/story4/homeku.html
{% extends 'story4/base.html'%} {% load static %} {% block content %}    
    <div class="row hero-content">

        <div class="column large-full">

            <h1>
            Hello, I'm Rafli, <br>
            a creative web developer <br>
            & designer currently <br>
            based somewhere.
            </h1>

        </div> 

    </div>
    <br>

    <div id="socmed">
        <h2>Find me on</h2>
        <a href="https://www.instagram.com/rafliamardito/" target="_blank">
          <img class="sospli" src="{% static 'story4/images/instagram.png' %}" alt="" alt="Ig @rafliamardito" width="50" height="50" hspace="20"/>
        </a>
        <a href="https://www.facebook.com/muhammadrafli.amardito" target="_blank">
          <img class="sospli" src="{% static 'story4/images/facebook.png' %}" alt="" width="50" height="50" hspace="20"/>
        </a>
        <a href="https://www.linkedin.com/in/rafli-amardito-2533bb192/" target="_blank">
          <img class="sospli" src="{% static 'story4/images/linkedin.png' %}" alt="" width="50" height="50" hspace="20"/>
        </a>
    </div>
{% endblock %}